# Default config: https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.0
#Layout/ExtraSpacing:
#  Enabled: false  # does not work with trailing comments
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Metrics/AbcSize:
  Max: 50
Metrics/BlockLength:
  Max: 200
Metrics/ClassLength:
  Enabled: false  # test classes are big
Metrics/LineLength:
  Max: 200
Metrics/MethodLength:
  Max: 50
Metrics/ModuleLength:
  Max: 200
Performance/RedundantBlockCall:
  Enabled: false  # prefer named block arguments for documentation
Style/ClassAndModuleChildren:
  Enabled: false  # we use both compact and nested style, preferring compact
Style/ClassVars:
  Enabled: false  # it's ok when knowing it's limitations, easy to access from class instance scope
Style/CollectionMethods:
  Enabled: true
Style/Copyright:
  Enabled: false  # we have copyright in the readme
Style/Documentation:
  Enabled: false  # we have documentation in the readme
Style/NumericPredicate:
  EnforcedStyle: comparison
Style/PercentLiteralDelimiters:
  Enabled: false  # it's better to use `%w{}` syntax, because the braces are the same as in `%r{}`
