# Jekyll
url: 'http://tkareine.org/jekyll-minibundle-example/'
baseurl: /jekyll-minibundle-example
source: .
destination: _site
exclude:
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - node_modules
  - package-lock.json
  - package.json
port: 8080
plugins:
  - jekyll/minibundle

# Minibundle
minibundle:
  minifier_commands:
    js: node_modules/.bin/uglifyjs
