# Jekyll
url: 'http://tkareine.org/jekyll-minibundle-example/'
baseurl: /jekyll-minibundle-example
source: .
destination: _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - node_modules
  - npm-shrinkwrap.json
  - package.json
port: 8080
gems: ['jekyll/minibundle']

# Minibundle
minibundle:
  minifier_commands:
    js: node_modules/.bin/uglifyjs -
